TEAM-PIN-UP/BE-PIN-UP

src/main/java/com/pinup/controller/PlaceController.java, src/main/java/com/pinup/global/maps/KakaoMapModule.java, src/main/java/com/pinup/service/PlaceService.java
> * #13 
* sort - distance: 거리 가까운 순으로 정렬 조건 추가
* 조회 범위 1000으로 수정
=> [ADD] 장소 조회 조건 수정(#13)

src/main/java/com/pinup/global/exception/ErrorCode.java, src/main/java/com/pinup/global/exception/PinUpException.java, src/main/java/com/pinup/service/FriendRequestService.java, src/main/java/com/pinup/service/FriendShipService.java
> 이미 친구인 회원에게 친구 요청을 보낼 수 있는 버그 수정
=> [Chore] 친구인 사람에게 친구 요청 보내는 예외 처리 추가

src/main/java/com/pinup/controller/PlaceController.java, src/main/java/com/pinup/controller/ReviewController.java, src/main/java/com/pinup/enums/PlaceCategory.java, src/main/java/com/pinup/enums/PlaceType.java, src/main/java/com/pinup/enums/SortType.java, src/main/java/com/pinup/repository/querydsl/PlaceRepositoryQueryDsl.java, src/main/java/com/pinup/repository/querydsl/PlaceRepositoryQueryDslImpl.java, src/main/java/com/pinup/service/PlaceService.java, src/main/java/com/pinup/service/ReviewService.java
* #31 
> 카테고리와 지정한 정렬 조건으로 친구 리뷰가 있는 장소 목록만 조회하는 기능 추가
=> 정렬 조건과 카테고리로 장소 목록 조회하는 API 개발

src/main/java/com/pinup/domain/bookmark/controller/BookMarkController.java, src/main/java/com/pinup/domain/bookmark/dto/request/BookMarkCreateRequest.java, src/main/java/com/pinup/domain/bookmark/dto/response/BookMarkResponse.java, src/main/java/com/pinup/domain/bookmark/service/BookMarkService.java
=> [Chore] BookMarkCreateRequest에 key값 추가(#44)

src/main/java/com/pinup/domain/bookmark/controller/BookMarkController.java, src/main/java/com/pinup/domain/bookmark/dto/request/BookMarkCreateRequest.java
=> [Chore] KakaoMapId -> KakaoPlaceId로 이름 통일(#44)

src/main/java/com/pinup/domain/bookmark/dto/response/BookMarkResponse.java
> Bookmark 조회시 review의 사진을 리턴하도록 수정
=> [Chore] Bookmark 조회시 review의 사진을 리턴하도록 수정(#44)

src/main/java/com/pinup/domain/bookmark/controller/BookMarkController.java, src/main/java/com/pinup/domain/bookmark/dto/response/BookMarkResponse.java, src/main/java/com/pinup/domain/bookmark/repository/BookMarkRepository.java, src/main/java/com/pinup/domain/bookmark/repository/querydsl/BookMarkRepositoryQueryDsl.java, src/main/java/com/pinup/domain/bookmark/repository/querydsl/BookMarkRepositoryQueryDslImpl.java, src/main/java/com/pinup/domain/bookmark/service/BookMarkService.java, src/main/java/com/pinup/domain/member/controller/MemberController.java, src/main/java/com/pinup/domain/member/repository/MemberRepository.java, src/main/java/com/pinup/domain/member/service/MemberService.java
=> 닉네임 검색 부분일치로 수정 및 북마크 필터링 추가

src/main/java/com/pinup/domain/alarm/service/AlarmService.java, src/main/java/com/pinup/domain/article/service/ArticleService.java, src/main/java/com/pinup/domain/friend/service/FriendRequestService.java, src/main/java/com/pinup/domain/member/dto/response/MemberReviewResponse.java, src/main/java/com/pinup/domain/member/entity/Member.java, src/main/java/com/pinup/domain/member/repository/MemberRepository.java, src/main/java/com/pinup/domain/member/service/AuthService.java, src/main/java/com/pinup/global/common/AuthUtil.java, src/main/java/com/pinup/global/config/jwt/JwtTokenProvider.java, src/test/java/com/pinup/global/jwt/JwtTokenProviderTests.java, src/test/java/com/pinup/service/AuthServiceTests.java
X
1. Token 키값 email -> socialId로 변경 
2. Swagger 정보 및 리뷰 작성일자 포맷 수정
=> 250215 토큰 고유 키값 및 리뷰 작성일자 포맷 수정

src/main/java/com/pinup/domain/member/controller/AuthController.java, src/main/java/com/pinup/domain/member/dto/request/LoginRequest.java, src/main/java/com/pinup/domain/member/dto/request/SignUpRequest.java, src/main/java/com/pinup/domain/member/entity/LoginType.java, src/main/java/com/pinup/domain/member/entity/Member.java, src/main/java/com/pinup/domain/member/service/AuthService.java, src/main/java/com/pinup/global/response/ErrorCode.java
* 앱 전용
* 앱 프론트에서 소셜 로그인 프로세스 전부 진행 후 데이터만 백엔드에 넘겨주는 로직으로 변경
=> [Feat] 회원가입/로그인 API 신규 개발

src/main/java/com/pinup/domain/member/controller/AuthController.java, src/main/java/com/pinup/domain/member/dto/request/LoginRequest.java, src/main/java/com/pinup/domain/member/dto/request/SignUpRequest.java, src/main/java/com/pinup/domain/member/entity/LoginType.java, src/main/java/com/pinup/domain/member/entity/Member.java, src/main/java/com/pinup/domain/member/service/AuthService.java
* 기존 ENUM 타입이 잘못 지정되어 있어 DB 초기화 후 재기입
* 프론트 요청으로 회원가입 API 응답 데이터 void로 변경
=> [Fix] 회원가입 에러 조치 및 DTO에 Validation 추가

src/main/java/com/pinup/global/config/jwt/JwtTokenProvider.java
1. Access Token, Refresh Token 유효시간 분리
=> [Fix] Access Token, Refresh Token 유효시간 분리

src/main/java/com/pinup/domain/place/controller/PlaceController.java, src/main/java/com/pinup/domain/place/dto/response/MapPlaceResponse.java, src/main/java/com/pinup/domain/place/repository/querydsl/PlaceRepositoryQueryDsl.java, src/main/java/com/pinup/domain/place/repository/querydsl/PlaceRepositoryQueryDslImpl.java, src/main/java/com/pinup/domain/place/service/PlaceService.java, src/main/java/com/pinup/global/common/Formatter.java
* 위치 정보 수집 동의하지 않는 유저의 경우에도 서비스 사용 가능
* 현 위치에서 떨어진 거리는 null로 반환
=> [Fix] 현위치 위/경도 필수값 해제

src/main/java/com/pinup/domain/member/dto/response/FeedResponse.java, src/main/java/com/pinup/domain/member/dto/response/MemberResponse.java, src/main/java/com/pinup/domain/member/service/MemberService.java
1. 피드 데이터에 relationType 필드 추가
2. MemberResponse에 리뷰 수, 평균 평점, 핀버디 수 필드 추가
=> Response에 누락된 데이터 추가 및 리팩토링

src/main/java/com/pinup/domain/friend/controller/FriendRequestController.java, src/main/java/com/pinup/domain/friend/repository/FriendRequestRepository.java, src/main/java/com/pinup/domain/friend/service/FriendRequestService.java, src/main/java/com/pinup/global/response/ResultCode.java
=> [Feat] 보낸 핀버디 신청 목록 조회 API 구현

src/main/java/com/pinup/domain/friend/controller/FriendRequestController.java, src/main/java/com/pinup/domain/friend/exception/FriendRequestSenderMismatchException.java, src/main/java/com/pinup/domain/friend/service/FriendRequestService.java, src/main/java/com/pinup/global/response/ErrorCode.java
=> [Feat] 핀버디 신청 취소 API 구현

src/main/java/com/pinup/global/config/redis/RedisConfig.java
> 해킹으로 인한 Redis 비밀번호 설정
1. [TTL 설정 없이도 Redis 저장 내용이 사라진다면](https://velog.io/@kny8092/TTL-%EC%84%A4%EC%A0%95-%EC%97%86%EC%9D%B4%EB%8F%84-Redis-%EC%A0%80%EC%9E%A5-%EB%82%B4%EC%9A%A9%EC%9D%B4-%EC%82%AC%EB%9D%BC%EC%A7%84%EB%8B%A4%EB%A9%B4)
2. [내 redis가 해킹당했다고? 심지어 local인데?](https://thxwelchs.github.io/%EB%82%B4redis%EA%B0%80%ED%95%B4%ED%82%B9%EB%8B%B9%ED%96%88%EB%8B%A4%EA%B3%A0%EC%8B%AC%EC%A7%80%EC%96%B4local%EC%9D%B8%EB%8D%B0/)
=> [Fix] Redis 비밀번호 설정

src/main/java/com/pinup/domain/friend/controller/FriendRequestController.java, src/main/java/com/pinup/domain/friend/controller/FriendShipController.java, src/main/java/com/pinup/domain/friend/repository/FriendRequestRepository.java, src/main/java/com/pinup/domain/friend/service/FriendRequestService.java, src/main/java/com/pinup/domain/friend/service/FriendShipService.java, src/main/java/com/pinup/domain/member/controller/MemberController.java, src/main/java/com/pinup/domain/member/service/MemberService.java
1. 핀버디 조회 관련 API 페이징 처리
2. 나의 텍스트/포토 조회 API 구현
=> 25.03.18 기능 요청서 반영

src/main/java/com/pinup/domain/member/dto/response/MemberResponse.java
> MemberResponse에 SNS Login Type 필드 추가
=> [Add] MemberResponse에 SNS Login Type 필드 추가

build.gradle, src/main/java/com/pinup/domain/member/controller/MemberController.java, src/main/java/com/pinup/domain/member/dto/request/UpdateMemberInfoAfterLoginRequest.java, src/main/java/com/pinup/domain/member/dto/request/UpdateProfileRequest.java, src/main/java/com/pinup/domain/member/entity/Member.java, src/main/java/com/pinup/domain/member/service/MemberService.java, src/main/java/com/pinup/global/config/s3/S3Service.java
* 닉네임 변경 시 @Audited를 통한 변경 이력관리
* 프로필 사진 변경 시 S3에서 기존 이미지 삭제 후 신규 이미지 업로드
* 닉네임, 소개글 length 수정
=> [Feat] 유저 정보 수정 API 구현

src/main/java/com/pinup/domain/friend/service/FriendShipService.java, src/main/java/com/pinup/domain/member/event/MemberEventListener.java, src/main/java/com/pinup/domain/member/service/AuthService.java
> 최초 회원가입 시 핀업 계정과 자동으로 핀버디 맺는 기능 추가
- 유저 생성 로직 수행 후 비동기로 핀업 계정과 핀버디 관계 형성
=> [Feat] 최초 회원가입 시 핀업 계정과 자동 핀버디 맺는 기능 추가

src/main/java/com/pinup/domain/friend/service/FriendRequestService.java, src/main/java/com/pinup/global/response/ErrorCode.java
> 친구 요청 후, 상대방이 수락 또는 거절하지 않고 본인에게 친구 요청 했을 때 예외 처리 추가
=> [Fix] 친구 요청 후, 상대방이 수락 또는 거절하지 않고 본인에게 친구 요청 했을 때 예외 처리 추가

src/main/java/com/pinup/domain/place/repository/querydsl/PlaceRepositoryQueryDslImpl.java
* query 값이 존재할 때 지도 경계 조건을 적용하지 않도록 변경
- 지도 경계 범위에 없지만, 지도에 등록된 장소 노출
* NPE 방지
- !String.isEmpty() 대신 StringUtils.hasText() 메서드 사용
=> [Fix] 지도 경계 기반 검색 로직 개선
